
const Dashboard = () => {
    return (
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla delectus quidem itaque expedita cumque eligendi reprehenderit. Repellat tempora, illo, autem nostrum deserunt, enim esse nesciunt exercitationem asperiores distinctio ex iure quis ut explicabo voluptas facilis reprehenderit illum impedit officiis quae debitis vitae recusandae nobis vel. Inventore consequatur eveniet dicta ea, quibusdam dignissimos quia. Hic vel eum quis ab nulla fugiat alias debitis maxime, dolores magnam sed sunt libero sapiente soluta, corrupti iste distinctio quaerat consequatur fuga voluptas? Facere nemo molestiae, blanditiis similique maiores ut, illum perspiciatis accusantium delectus sequi numquam accusamus cupiditate sapiente aut rem, necessitatibus debitis sint ipsam aspernatur. Molestias facilis quidem, delectus id dolorem non placeat ipsam dolore nisi assumenda in et, quo natus sunt. Facilis fugit error explicabo minima! Nihil quo fugiat obcaecati ipsa aut velit dolorem adipisci distinctio saepe quibusdam fugit, porro expedita labore quae, eum iste est, minima minus odio non? In explicabo consequuntur cum similique impedit fugit voluptates, temporibus a reprehenderit voluptatum ullam officiis ab voluptatibus mollitia dolor, distinctio iusto tenetur necessitatibus totam! Ad molestias, accusantium quo cupiditate repellat rem sit. Error unde dicta incidunt iusto deserunt recusandae perferendis facere perspiciatis in! Perferendis quibusdam soluta velit quisquam adipisci vitae nostrum illo, cum molestiae dolorum, odio exercitationem delectus qui molestias dolor officiis illum doloremque, alias quos cupiditate sunt rerum corrupti ratione recusandae? Quasi eum provident sequi repellat distinctio laudantium sunt culpa aspernatur nulla, obcaecati cupiditate illo eaque esse nihil possimus! Praesentium nesciunt possimus atque rem dolor debitis placeat, reprehenderit quam necessitatibus a illum ab hic, consequuntur exercitationem reiciendis ducimus quia. Voluptatibus perferendis ipsum qui, reiciendis ex earum nostrum suscipit officiis amet minima, sed est. Quam impedit dignissimos unde ab expedita illo corrupti saepe a explicabo beatae incidunt, nulla doloremque, porro animi quod facilis laboriosam! Nihil nostrum minus facilis animi reprehenderit amet dolore dolor, nulla saepe!
        </div>
    )
}

export default Dashboard